### PR TITLE
PDF Downloader App

### PR DESCRIPTION
**Pull request by G0V1NDK**
# Pull Request for Play With Python 💡

## Issue Title : PDF Downloader script

- **Info about the related issue (Aim of the project)** : Create a PDF Downloader App using Python
- **Name:** Govind Kushwaha
- **GitHub ID:** @G0V1NDK
- **Email ID:** [govind.kush2001@gmail.com](mailto:govind.kush2001@gmail.com)
- **Idenitfy yourself: (Mention in which program you are contributing in.)** Codepeak'22

Closes: #95 issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

In this, we will input the URL of the (.pdf) extension and the pdf file be downloaded at the specified path. A basic approach is used for creating this program. Using the (requests) library we are requesting access to the file from the given URL.

## Type of change ☑️

All things are updated in README.md file.

### CODE REVIEW

**Comment by G0V1NDK** [comment]
This PR will close: https://github.com/World-of-ML/Play-With-Python/issues/95

@abhisheks008

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the project structure and add images of your project accordingly.

**Comment by G0V1NDK** [comment]
@abhisheks008 Now you can check it.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Project structure will be like this,
```
PDF Downloader App
|-- pdf_downloader.py
|-- README.md
|-- Images
    |-- image1.png
    |-- image2.png
    |-- image3.png
|-- requirements.txt
```

**Comment by G0V1NDK** [comment]
@abhisheks008 how about now?

**Comment by G0V1NDK** [comment]
Okay. Then I will try the GUI version by using Tkinter.
I'll let you know when it's done.

**Comment by G0V1NDK** [comment]
@abhisheks008 Done the interactive GUI version for the PDF Downloader. You can check the output from readme.md and image folder as well.

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@G0V1NDK

**Pull request merged**
