### PR TITLE
Haunted House[GUI]

### PR DESCRIPTION
**Pull request by bcsamrudh**
# Pull Request for Play With Python 💡

## Issue Title : [Enhancement] Haunted House Game - Add GUI 

- **Info about the related issue (Aim of the project)** : To add GUI to the Haunted House Program
- **Name:** B C Samrudh
- **GitHub ID:** https://github.com/bcsamrudh
- **Idenitfy yourself: (Mention in which program you are contributing in.)** DWOC23

Closes: #159 

Added a GUI to the program Haunted House

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The project is not yet completed

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by bcsamrudh** [comment]
@abhisheks008. There are 2 issues with the program. Could you help me solve them?

**Comment by bcsamrudh** [comment]
@abhisheks008. I tried to create a scrollbar, but the scrollbar did not work.

**Review by abhisheks008 — APPROVED** [review]
Approved. Make a PR.

**Comment by abhisheks008** [comment]
> @abhisheks008. I tried to create a scrollbar, but the scrollbar did not work.

Don't worry. That'll be figure out by another contributor. Nice effort.

**Comment by bcsamrudh** [comment]
> Approved. Make a PR.

A PR has been made!

**Pull request merged**
