### PR TITLE
Created Currency Converter

### PR DESCRIPTION
**Pull request by pundarikaksha7**
# Pull Request for Play With Python 💡

## Issue Title : #83 

- **Info about the related issue (Aim of the project)** : Created Currency Converter
- **Name:** Pundarikaksha
- **GitHub ID:** pundarikaksha7
- **Email ID:** pundarikakshamohanty@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in.)** CodePeak

Closes: #83 Currency Converter

### Describe the add-ons or changes you've made 📃

Created a Currency Converter directory.

## Type of change ☑️

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Tested and tried on local machine

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
I am expecting an user interactive GUI version as we are building here apps. The console one is okay, but try to make the GUI version of it.

**Comment by pundarikaksha7** [comment]
Kindly mention wherever you want a GUI. I spent a lot of time to do this without GUI xD. Alright I will rewrite it.

**Comment by abhisheks008** [comment]
Whenever you are going to create an application, I don't the user is gonna expecting a console based interface, rather they will be expecting a GUI based setup. Anyways my bad, I'll keep that in mind while mentioning in the issues.

**Review by abhisheks008 — APPROVED** [review]
PR approved and ready to be merged.
@pundarikaksha7

**Pull request merged**
