### PR TITLE
Maze Game

### PR DESCRIPTION
**Pull request by pundarikaksha7**
# Pull Request for Play With Python 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Pundarikaksha
- **GitHub ID:** pundarikaksha7
- **Email ID:** pundarikakshamohanty@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in.)** CodePeak

Closes: #25 

### Describe the add-ons or changes you've made 📃

Created maze game
run using
# python3 pymaze.py -interactive -block -color -width 20 -height 15
# height and width can be adjusted to fit corresponding command line

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️
Tested on personal terminal

## Checklist: ☑️

- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [ x] I have added things that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Everything looks good. But add a `README.md` file following the [README template](https://github.com/World-of-ML/Play-With-Python/blob/main/.github/readme_template.md).

@pundarikaksha7

**Comment by pundarikaksha7** [comment]
Created a readme file.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Can you elaborate the README file, it's just an one liner kind of a stuff you have done. README file will be the face of your project, others will get to know from that README file what you are showcasing to them. Please elaborate your README file properly, also add the demonstration images there as per the template given to you.

**Comment by pundarikaksha7** [comment]
Okay I will. Actually I was in a hurry as my flight is about to take off XD.

**Comment by abhisheks008** [comment]
Oops!🤣
No worries take your time it's just the beginning of the program.

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged!
@pundarikaksha7

**Pull request merged**
