### PR TITLE
Hacking Mini Game

### PR DESCRIPTION
**Pull request by SSHSRN**
Signed-off-by: SRIHARI S <sshsrn@gmail.com>

# Pull Request for Play With Python 💡

## Issue Title : #42 

- **Info about the related issue (Aim of the project)** : Implement the hacking mini game using python
- **Name:** Srihari S
- **GitHub ID:** SSHSRN
- **Email ID:** sshsrn@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in.)** Codepeak-2022

Closes: #42 

### Describe the add-ons or changes you've made 📃

I have implemented the hacking mini game using python by using the random module, looping, conditional statements and functions.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I tested the code in my own computer by executing the program and validating the output obtained against the expected output.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SSHSRN** [comment]
@abhisheks008 Kindly check!

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the project structure and add Images of your project accordingly.

**Comment by SSHSRN** [comment]
I have added the images as requested. @abhisheks008 Kindly check!

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Create a folder named `Images` add put your images there too. For reference you can check out other projects here in this repository.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me! Your PR is approved and ready to be merged.
@SSHSRN

**Pull request merged**
